### ISSUE TITLE
Where can I get "J_regressor_halpe.npy" file?

### ISSUE THREAD

**Issue by FedraB** [boycehbz/GroupRec#1]
Hi, thank you for sharing your work!

When executing your third step of "Getting Started" it returned a FileNotFoundError regarding a J_regressor_halpe.npy file that should be in "data" and is being used in line 19 on "utils\smpl_torch_batch.py", but I couldn't find it anywhere.

Could you tell me where to get that file?

**Comment by boycehbz** [comment]
Hi, thank you for your feedback!
I have uploaded the missing file. You may pull the latest repo.

**Comment by FedraB** [comment]
Thank you!!
